### ISSUE TITLE
Array Context: do inputs to call_loopy need to be thawed?

### ISSUE THREAD

**Issue by inducer** [inducer/meshmode#107]
Not currently defined.

cc @kaushikcfd

**Comment by inducer** [comment]
I'm not sure. For arithmetic, I think requiring thawing makes sense. For `call_loopy`, the array context is supplied (as the `self` argument to `call_loopy`), so it's less clear that it's needed.

**Comment by inducer** [comment]
For the PyOpenCL array context, passing an un-thawed array is hypothetically fine: It's a constant array that doesn't have a queue.

For the lazy array context, we *could* define passing an un-thawed array as implicitly producing a `DataWrapper`, with similar semantics.

**Comment by inducer** [comment]
@kaushikcfd, what do you think?

**Comment by kaushikcfd** [comment]
Agree with the proposal that frozen read-only array inputs should be thawed inside `call_loopy`. It doesn't introduce any performance hits and provides a more convenient interface.

**Comment by inducer** [comment]
> frozen read-only array inputs should be thawed inside call_loopy

What is "thawing" to you anyway, in this instance? (Remember we're trying to define semantics here IMO: It's not a given what that means.) To me: thawing in CL means "add a queue", thawing in lazy means... hm... stick in a `DataWrapper`. Maybe `thaw` is what I wanted anyay. :)

**Comment by kaushikcfd** [comment]
I thought the semantics for "thaw"-ing lazy arrays was already defined in #104. The same can be transmitted to the thawing in the context of `call_loopy`, which I believe is reasonable.

**Comment by inducer** [comment]
Fair.

I guess the main question then is whether we'll require the user to explicitly thaw, or whether we'll implicitly do what's necessary in `call_loopy`. FWIW, IMO if we do anything implicitly, we should only do so for read-only arrays.

Upside of implicit treatment:
- Convenience

Downside of implicit treatment:
- We may wind up with a few separate `DataWrapper`s for the same data. (that are, however, pretty straightforward to clean up)

**Comment by kaushikcfd** [comment]
I vote for the implicit treatment. I think the benefits of a cleaner interface outweigh the downsides of a polluted `pt.Namespace()`.

**Comment by inducer** [comment]
OK, implicit is good by me. Ready to close?

**Comment by kaushikcfd** [comment]
Yep, resolved from my end too.
