### ISSUE TITLE
Updating how we flatten DOF arrays in anticipation for lazy evaluation

### ISSUE THREAD

**Issue by thomasgibson** [inducer/meshmode#198]
This issue is specifically addressing how to update the flatten routine for DOFArrays, found here: https://github.com/inducer/meshmode/blob/bbec89ae7b8cc82a42696b4efd9a0f6beb7ee741/meshmode/dof_array.py#L381-L412

Basically, the summary of the problem is that we need to remove stateful updates of the array since this will break lazy-evaluation. The intent of #192 is to hunt down and update all instances of stateful array updates in meshmode. Specifically for the flattening routines, this bit of code is the main culprit we need to get ride of: https://github.com/inducer/meshmode/blob/bbec89ae7b8cc82a42696b4efd9a0f6beb7ee741/meshmode/dof_array.py#L404-L410

What was originally proposed in #192 (which I really liked :disappointed:) was:
```python
def _flatten_dof_array(ary: Any, strict: bool = True):
    if not isinstance(ary, DOFArray):
        if strict:
            raise TypeError(f"non-DOFArray type '{type(ary).__name__}' cannot "
                    "be flattened; use 'strict=False' to allow other types")
        else:
            return ary

    actx = ary.array_context
    if actx is None:
        raise ValueError("cannot flatten frozen DOFArrays")

    return actx.np.concatenate([actx.np.reshape(grp_ary, -1)
                                for grp_ary in ary])
```
_But_, turns out this isn't what we want to do since we want to maintain flexibility with regards to the memory layout of the array (x-ref: https://github.com/inducer/meshmode/pull/192#discussion_r638401854).

I would appreciate some guidance on how to proceed forward now that #196 is in. cc @alexfikl, @inducer

**Comment by inducer** [comment]
The only difference is that the flatten kernel needs to stick and be used in place of the reshape. (The reshape can be used if the strides are right, as with the code in #154).
