### ISSUE TITLE
dof_array.flat_norm is CL-specific

### ISSUE THREAD

**Issue by kaushikcfd** [inducer/meshmode#219]
cf.
https://github.com/inducer/meshmode/blob/f87576dedf373c785172e20d0fb956c7194c2ba6/meshmode/dof_array.py#L645-L646

**Comment by kaushikcfd** [comment]
Why does `flat_norm` flatten a group's values before computing the norm?

```python
In [2]: a = np.random.rand(3, 3)

In [3]: np.linalg.norm(a)
Out[3]: 1.899203808354709

In [4]: np.linalg.norm(a.reshape(-1))
Out[4]: 1.899203808354709
```

**Comment by kaushikcfd** [comment]
> Why does flat_norm flatten a group array before computing the norm?

Oops forgot my 450 here. Feel free to ignore this.

**Comment by inducer** [comment]
To be fair, I think numpy defaults to Frobenius, which is equivalent to a flattened 2-norm for 2D arrays. For (say 3D) tensor product elements, the shape will likely be `(nelements, Np, Np, Np)`, which would just be an error in numpy, making the flatten necessary after all.
