### ISSUE TITLE
ArrayContext.np.sqrt fails for device scalars

### ISSUE THREAD

**Issue by alexfikl** [inducer/meshmode#237]
Doing a norm-like operation
```
actx.np.sqrt(actx.np.sum(x**2))
```
doesn't work after the transformations from #236. It seems like `actx.np.sqrt` doesn't like getting a scalar from `sum` and fails in this check

https://github.com/inducer/meshmode/blob/d95cb2a1e6462a1e2aed3dfe13b9881a00db1122/meshmode/array_context.py#L93-L96

The same probably holds for any other elementwise operation in `actx.np`.

**Comment by alexfikl** [comment]
Actually this doesn't seem to have worked with the transformations from `arraycontext.PyOpenCLArrayContext` either. Should it work?

**Comment by inducer** [comment]
That conditional is a bit rigid in retrospect. It's fine to relax that (and not tag any inames as a result).

**Comment by alexfikl** [comment]
Tried just adding a `continue` instead of the `raise` in there, but loopy doesn't appreciate it either and fails here (next to a FIXME)

https://github.com/inducer/loopy/blob/e232bb1361479f2e6fd3bd7efd7f4ecce270947f/loopy/target/c/codegen/expression.py#L152-L155

(the offset is `lp.auto`)

**Comment by inducer** [comment]
(As a workaround, you could just `**0.5` for now.)

**Comment by inducer** [comment]
IIUC, @kaushikcfd just applied the meshmode half of this fix in #243. Now it's just the loopy FIXME that remains.

Somewhat related: https://github.com/inducer/loopy/pull/453/

**Comment by kaushikcfd** [comment]
> Tried just adding a continue instead of the raise in there, but loopy doesn't appreciate it either and fails here (next to a FIXME)

Trying out a solution here: https://github.com/inducer/loopy/pull/454/files

**Comment by alexfikl** [comment]
Just tried it out and can confirm that this seems to work with inducer/loopy#453 and inducer/loopy#454
```
from meshmode import _acf
actx = _acf()
x = actx.zeros(4, np.float64) + 4
actx.np.sqrt(actx.sum(x))
```

**Comment by inducer** [comment]
I will revert the "solution" to this, see https://github.com/inducer/loopy/pull/453#issuecomment-1644804170. We will have to come up with a different way to solve this.
