### ISSUE TITLE
Tolerance too strict in _test_node_vertex_consistency_resampling

### ISSUE THREAD

**Issue by matthiasdiener** [inducer/meshmode#310]
We have seen lots of errors like these:

```
"/Users/mdiener/Work/efuse/meshmode/meshmode/mesh/__init__.py", line 1207, in _test_node_vertex_consistency
    assert _test_node_vertex_consistency_resampling(mesh, mgrp, tol)
  File "/Users/mdiener/Work/efuse/meshmode/meshmode/mesh/__init__.py", line 1195, in _test_node_vertex_consistency_resampling
    assert max_el_vertex_error < tol*size, max_el_vertex_error
AssertionError: 1.144170793882154e-15
```

This is the code:
https://github.com/inducer/meshmode/blob/48abe4bedf5e54e57fca392756423b6f45abff9a/meshmode/mesh/__init__.py#L1178

**Comment by alexfikl** [comment]
What sort of meshes are these? I've only been able to trigger that if there was actually something weird with the mesh.

You can work around it from the outside by setting `node_vertex_consistency_tolerance` in the mesh constructor:
https://github.com/inducer/meshmode/blob/c1ff399316fc15938723433a3308f0710751e11b/meshmode/mesh/__init__.py#L919

**Comment by matthiasdiener** [comment]
We have seen it most recently with this: https://github.com/illinois-ceesd/drivers_y2-isolator/tree/main/data/3D/eightX_injection

**Comment by alexfikl** [comment]
Hm, I don't think the gmsh reader has a way to pass down the tolerance (most things in `mesh.generation` do), so this might need a bit of work.

**Comment by alexfikl** [comment]
@matthiasdiener I just tried that mesh with just
```
from meshmode.mesh.io import read_gmsh
mesh = read_gmsh("isolator.msh")
```
and it didn't throw an error for me, weirdly. What version of `gmsh` are you using?

**Comment by matthiasdiener** [comment]
These errors seem to be dependent on rank numbers as well. I tried https://github.com/illinois-ceesd/drivers_y2-isolator/test_mesh/lazy/oneX with 32 ranks, which does not trigger assertion, but 64 ranks trigger it.

**Comment by alexfikl** [comment]
> These errors seem to be dependent on rank numbers as well. I tried [illinois-ceesd/drivers_y2-isolator/test_mesh/lazy/oneX](https://github.com/illinois-ceesd/drivers_y2-isolator/test_mesh/lazy/oneX) with 32 ranks, which does not trigger the assertion above, but 64 ranks trigger it.

Do the partitions look reasonable? 

The error in the check is relative `tol * size`, where `size` is the bounding box of the mesh and `tol ~ 1.0e-13`. The only way I can see that failing like in your original report is if the `size` is very small for some reason.. Hm..

**Comment by inducer** [comment]
> Could we use the size of the bounding box of each element individually?

I like that idea. Since this is an element-scale error, comparing to another element-scale quantity is likely a better idea (and more robust) than anything to do with the overall mesh size.

@majosm, could you do a PR?

**Comment by majosm** [comment]
@matthiasdiener Can you try #316 on some of your isolator runs? (It should be independent of partitioning now; just want to make sure the tolerance isn't too tight.)
