### ISSUE TITLE
Resampling can lead to expressions that index along a 0-long axis 

### ISSUE THREAD

**Issue by kaushikcfd** [inducer/meshmode#321]
Expressions like these: https://github.com/inducer/meshmode/blob/cfe8346044d1333ec9ab75e03734cb7addedd2b4/meshmode/discretization/connection/direct.py#L688-L692

could lead to expressions like --
```python
def main(np):
    ary = np.zeros((0, 10))
    idx1 = np.arange(10, dtype="int32").reshape(-1, 1)
    idx2 = np.zeros((10, 5), dtype="int32")

    np.where(True, np.ones((10, 5)), ary[idx1, idx2])


if __name__ == "__main__":
    import numpy as np
    main(np)
```

notice how the expression in `main()` function is only valid for lazy array packages. Another point to note is that `jax` (unlike pytato) makes indexing into 0-long axes illegal to begin with.

**Comment by inducer** [comment]
I'm OK with making those illegal in pytato as well! IIUC, this is easy to avoid. If the source element group is empty, we can just skip that contribution.
