### ISSUE TITLE
Loopy cache collision in CI

### ISSUE THREAD

**Issue by inducer** [inducer/meshmode#335]
Pointed out by @alexfikl in https://github.com/inducer/meshmode/pull/334#issuecomment-1152986288.

**Comment by kaushikcfd** [comment]
Has been there since https://github.com/inducer/meshmode/pull/254. That was the PR when we started testing against `PytatoPyOpenCLArrayContext`.

**Comment by inducer** [comment]
Should be fixed by https://github.com/inducer/loopy/pull/628.

**Comment by kaushikcfd** [comment]
Re-triggered the CI on `main` to verify that the warning is gone. After which we can close this!

**Comment by kaushikcfd** [comment]
Looks like the CI is clean. Thanks for the report @alexfikl!
