### ISSUE TITLE
Performance of `generate_box_mesh`

### ISSUE THREAD

**Issue by MTCam** [inducer/meshmode#350]
`generate_box_mesh` appears to be taking an inordinate amount of time.  This seems to be due primarily to the part of the generator that determines facial adjacency to domain boundaries.  

For every boundary (including periodic boundaries), the code loops through all elements, and determines adjacency for each face in the element.   For large (10s of millions of elements) with several boundaries (i.e. like those used in CEESD), box grid generation is taking hours.

One thing we can do to help make this a little faster is to [reorder the loops such that every element is visited only once](https://github.com/inducer/meshmode/pull/351), and checked against every boundary (i.e. instead of visiting every element for every boundary).   The following table are the generation times for a 3D periodic mesh with "original" loop ordering, and "modified" loop ordering:

number of elements | original | modified
-------------------- | -------- | --------
48k                            | 6s           |   2s
96k                            | 12s         |   4s
192k                          | 25s         |   9s
384k                         | 48s         |  19s
768k                         | 100s       |  32s
1.5M                          | 205s      |  87s

**Comment by majosm** [comment]
I'm looking into whether we can change the interface to `_compute_facial_adjacency_from_vertices` to pass in a tag/face mapping that can be computed more efficiently. The current `frozenset(fvi)` dictionary approach precludes us from using numpy for this code, so it ends up being pretty slow.
