### ISSUE TITLE
Distributed setup calls _make_cross_face_batches once per face

### ISSUE THREAD

**Issue by inducer** [inducer/meshmode#36]
[Here](https://github.com/inducer/meshmode/blob/2f84174f03ec9164c3c314b9eb9cdb2c4bd41db7/meshmode/discretization/connection/opposite_face.py#L443-L522). It definitely shouldn't. As the name possibly suggests, `_make_cross_face_batches` is supposed to be a batched routine. (called once per rank pair) @MTCam spotted this when doing some parallel runs.

This is actually pretty bad, since it creates lots of small interpolation batches rather than one big one.

**Comment by inducer** [comment]
@majosm, would you be willing to take a look at this?

**Comment by inducer** [comment]
> This is actually pretty bad, since it creates lots of small interpolation batches rather than one big one.

The impact of that is that MPI buffer packing is essentially a Python loop over elements

**Comment by MTCam** [comment]
Doesn't this issue also affect wave-eager examples?

**Comment by inducer** [comment]
It does.
