### ISSUE TITLE
TP element orientation flips on Gmsh read

### ISSUE THREAD

**Issue by inducer** [inducer/meshmode#394]
@MTCam reports that this mesh has consistently-oriented elements in gmsh that become inconsistently-oriented when read into meshmode:

```
$MeshFormat
2.2 0 8
$EndMeshFormat
$Nodes
9
1 -1 -1 0
2 1 -1 0
3 1 1 0
4 -1 1 0
5 0 -1 0
6 1 0 0
7 0 1 0
8 -1 0 0
9 0 0 0
$EndNodes
$Elements
4
1 3 2 0 1 4 8 9 7
2 3 2 0 1 3 7 9 6
3 3 2 0 1 2 6 9 5
4 3 2 0 1 1 5 9 8
$EndElements
```

**Comment by inducer** [comment]
This mesh does *not* have consistent ordering:

![image](https://github.com/inducer/meshmode/assets/352067/cc27655e-0077-4818-8508-fa26c8d001e5)

(I've just drawn arrows along gmsh's specified first two elements: `4 8 9 7` and `3 7 9 6`.)

If this came out of Gmsh as shown, then it serves as a good example of my claim that Gmsh may produce elements of varying orientation.

Meshmode currently has an unhelpful behavior where it renumbers the vertices according to the order in which they occur in elements. I'll have a PR that removes that behavior shortly. In addition, meshmode converts from gmsh node ordering to lexicographic, but it's straightforward to verify that it does so consistently:

```
[[4 7 8 9]
 [3 6 7 9]
 [2 5 6 9]
 [1 8 5 9]]
```

**Comment by MTCam** [comment]
> This mesh does _not_ have consistent ordering:
> 
> ![image](https://private-user-images.githubusercontent.com/352067/325388294-cc27655e-0077-4818-8508-fa26c8d001e5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5OTY1NDAsIm5iZiI6MTcxMzk5NjI0MCwicGF0aCI6Ii8zNTIwNjcvMzI1Mzg4Mjk0LWNjMjc2NTVlLTAwNzctNDgxOC04NTA4LWZhMjZjOGQwMDFlNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyNFQyMjA0MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNmMxMjRmZGQzZjg4MzU5YTI4MmQyZWE0YTE5YzU0N2ZhZGYyZjVlM2Q1ZWE4NjU0YTQ1YjhjY2NiYzVhNzkxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jcXVqMiGiMncJzet1dcxaTHL4qi3oudfabIzvVwi5Jg)
> 
> (I've just drawn arrows along gmsh's specified first two elements: `4 8 9 7` and `3 7 9 6`.)
> 
> If this came out of Gmsh as shown, then it serves as a good example of my claim that Gmsh may produce elements of varying orientation.
> 
> Meshmode currently has an unhelpful behavior where it renumbers the vertices according to the order in which they occur in elements. I'll have a PR that removes that behavior shortly. In addition, meshmode converts from gmsh node ordering to lexicographic, but it's straightforward to verify that it does so consistently:
> 
> ```
> [[4 7 8 9]
>  [3 6 7 9]
>  [2 5 6 9]
>  [1 8 5 9]]
> ```

I think it depends on how you are defining orientation.  In gmsh, and in my previous experience with meshes, the orientation is defined by the direction of the normal vector, which is consistently oriented for this gmsh mesh.  All of these elements have a normal that points out of the page at the reader.

**Comment by inducer** [comment]
You're right, those arrows are both counterclockwise. Somehow I convinced myself otherwise, don't know how. :thinking: 

I've since added a mesh orientation finder and fixer to Meshmode (PRs soon). The good news is that the mesh orderings are still consistent after meshmode converts to lexicographic order, but somehow meshmode thinks of these elements as negatively oriented, which it probably shouldn't.

**Comment by MTCam** [comment]
> You're right, those arrows are both counterclockwise. Somehow I convinced myself otherwise, don't know how. 🤔
>
Heh, I have a lot of experience with that exact phenomenon.
 
> I've since added a mesh orientation finder and fixer to Meshmode (PRs soon). The good news is that the mesh orderings are still consistent after meshmode converts to lexicographic order, but somehow meshmode thinks of these elements as negatively oriented, which it probably shouldn't.

FWIW, my strategy was to look at it element-by-element , apply the meshmode reordering and if it resulted in a negatively oriented element, then swap the vertices in the gmsh connectivity such that the meshmode reader would get a properly oriented element.   Because my test meshes were all simple, single block, I could apply the same vertex swap to every element in a given mesh and just write a gmsh mesh file that meshmode could read and get a good mesh.   

The current crux is that with the more complex, multiblock meshes that are filled with re-combined triangles/tets --> quads/hexes, I need to _actually_ look at it element-by-element and swap vertices so that meshmode gets an element like it expects.   I would have preferred to fix it up within the meshmode gmsh ingest toolchain, but I had a bit of trouble piecing together how it was remapping the faces and that mapping's correspondence with the volume element connectivity.

**Comment by inducer** [comment]
This was fixed by https://github.com/inducer/gmsh_interop/pull/31.
