### ISSUE TITLE
3d element orientation for hexes

### ISSUE THREAD

**Issue by anderson2981** [inducer/meshmode#403]
I've attached a gmsh mesh and .geo file used to generate it. This mesh has a node ordering that is inconsistent with the lexicographic vertex reshuffle for hexahedral elements used in meshmode. 

An example run on the mesh in question:

![image](https://github.com/inducer/meshmode/assets/41346365/fe9d2bc9-7769-4869-a597-58486e0a7bfd)
![image](https://github.com/inducer/meshmode/assets/41346365/445b540d-3435-411f-86a1-552a8a1bdba5)

if I modify the vertex ordering by swapping 1 with 4 and 7 with 2 I can produce a working mesh

![image](https://github.com/inducer/meshmode/assets/41346365/71bc5377-f94c-40ce-86d6-99b6103235eb)

**Comment by anderson2981** [comment]
`Point(1) = { 0.0,  -0.01, 0, 0.01};
Point(2) = { 0.1, -0.01, 0, 0.01};
Point(3) = { 0.1, 0.01, 0, 0.01};
Point(4) = { 0.0,  0.01, 0, 0.01};
Point(5) = { 0.12000000000000001,  -0.01, 0, 0.01};
Point(6) = { 0.12000000000000001,  0.01, 0, 0.01};
Line(1) = {1, 2};
Line(2) = {2, 3};
Line(3) = {3, 4};
Line(4) = {4, 1};
Line(5) = {3, 6};
Line(6) = {2, 5};
Line(7) = {5, 6};
Line Loop(1) = {-4, -3, -2, -1};
Line Loop(2) = {2, 5, -7, -6};
Plane Surface(1) = {1};
Plane Surface(2) = {2};

fluid_surface_vector[] = Extrude {0, 0, 0.02} { Surface{1}; };
wall_surface_vector[] = Extrude {0, 0, 0.02} { Surface{2}; };
Coherence;
Physical Volume('fluid') = {fluid_surface_vector[1]};
Physical Volume('wall_insert') = {wall_surface_vector[1]};
Physical Surface('inflow') = {fluid_surface_vector[2]};
Physical Surface('outflow') = {fluid_surface_vector[4]};
Physical Surface('flow') = {
    fluid_surface_vector[2],
    fluid_surface_vector[4]
};
Physical Surface('isothermal_wall') = {
    1,
    fluid_surface_vector[0],
    fluid_surface_vector[3],
    fluid_surface_vector[5]
};
Physical Surface('wall_interface') = {fluid_surface_vector[4]};
Physical Surface('wall_farfield') = {
    2,
    wall_surface_vector[0],
    wall_surface_vector[3],
    wall_surface_vector[4],
    wall_surface_vector[5]
};

Transfinite Curve {1, 3, 10, 12} = 0.1 / 0.01 + 1;
Transfinite Curve {5, 6, 32, 34} = 0.02 / 0.01 + 1;
Transfinite Curve {2, 4, 7, 9, 11, 33}=0.02/0.01 + 1 Using Bump 1/1;Transfinite Curve {14, 23, 45, 15, 19, 41}=0.02/0.01 + 1 Using Bump 1/1;
Transfinite Surface {1, 2} Left;
Transfinite Surface {29, 51} Right;
Transfinite Surface {28, 50} Left;
Transfinite Surface {20, 42} Right;
Transfinite Surface {16, 46} Left;
Transfinite Surface {24} Right;
Transfinite Volume {1, 2};

Mesh.MeshSizeExtendFromBoundary = 0;
Mesh.MeshSizeFromPoints = 0;
Mesh.MeshSizeFromCurvature = 0;

Mesh.Algorithm = 5;
Mesh.OptimizeNetgen = 1;
Mesh.Smoothing = 100;

// Convert the triangles back to quads
Mesh.Algorithm = 6;
Mesh.Algorithm3D = 1;
Mesh.RecombinationAlgorithm = 2;
Mesh.RecombineAll = 1;
Recombine Surface {1, 2};`

**Comment by anderson2981** [comment]
I couldn't figure out how to attach the meshes, here they are in ascii

https://gist.github.com/anderson2981/8183b49a9db1a71d261ba41a8a3b2fe1

**Comment by anderson2981** [comment]
A more complicated example, for which I have no solution as of yet.

<img width="1229" alt="image" src="https://github.com/inducer/meshmode/assets/41346365/a1b6c3a8-b81b-4ae5-80b8-dcf30956f79c">

**Comment by anderson2981** [comment]
@inducer

**Comment by inducer** [comment]
Been digging into this a bit. I've learned that, for the simple mesh once read by meshmode, the normals point inward.
