### ISSUE TITLE
Recent update breaks mirgecom 

### ISSUE THREAD

**Issue by MTCam** [inducer/meshmode#412]
This update appears to break TPE in mirgecom.
https://github.com/inducer/meshmode/commit/4cb7c84eb892120817a36b2219eef4596f05c3fd

Now, use of TPE in mirgecom gets this error:
```
                # FIXME: can be gotten rid of by updating meshmode operators
>               basis_1d = out_grp.bases_1d()
E               AttributeError: 'LegendreGaussLobattoTensorProductElementGroup' object has no attribute 'bases_1d'
grudge/grudge/op.py:766: AttributeError
```

It was not entirely clear to me how to fix up our `grudge/op` to be compatible with this change.

**Comment by inducer** [comment]
See @a-alveyblanc's comment on #409.
