### ISSUE TITLE
Make refiner work in 1D

### ISSUE THREAD

**Issue by inducer** [inducer/meshmode#6]
@guptashvm: The refiner should also work in 1D, i.e. just some line segments strung together. Fortunately, the connectivity computation there should be effectively trivial. @mattwala is currently trying to make that happen. Any comments on gotchas and things that may not be straightforward?

**Comment by mattwala** [comment]
@guptashvm, @inducer, I think I have figured out how to make the 1D case work (merge request is in gitlab). It was a fairly easy change to make. I think you can close this issue.

**Comment by inducer** [comment]
Great! I'll close this and look at the MRs tomorrow. @guptashvm, I've added you to the project on gitlab.
