### ISSUE TITLE
ValueError: could not broadcast input array from shape (3,3) into shape (3,4) in test_quad_mesh_2d[3-ball-radius-1.step]

### ISSUE THREAD

**Issue by inducer** [inducer/meshmode#62]
https://gitlab.tiker.net/inducer/meshmode/-/jobs/178270

This seems related to #56. @alexfikl, could you take a look?

**Comment by alexfikl** [comment]
Hm, seems like the gmsh reader isn't happy with some of the rectangular elements. I'll give it a look!
