### ISSUE TITLE
Reductions in `ArrayContext.np` behave differently from `numpy`

### ISSUE THREAD

**Issue by xywei** [inducer/meshmode#91]
When the reduction result is a scalar,
- reductions in `numpy`, e.g., `numpy.sum`, `numpy.max`, return a scalar value, while
- reductions in `ArrayContext.np` return an array of size one.

This difference affects, for example, [gmres residual reporting in pytential](https://github.com/inducer/pytential/blob/10c2ea345e69367cfbba67ba5aa2954ebac467cf/pytential/solve.py#L252), where the formatting `.8e` will cause an error if `norm` is an array.

**Comment by inducer** [comment]
Thanks for the report! #92

**Comment by inducer** [comment]
That wasn't completely it: https://github.com/inducer/pytential/pull/41/commits/c25cf71bbc4be723f9bc8bb46e3a7e2097861d26
